# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeCoxDirection <- function(x, comp, n_points, verbose) {
    .Call(`_opdesmixr_computeCoxDirection`, x, comp, n_points, verbose)
}

getScheffeGaussian <- function(X, order) {
    .Call(`_opdesmixr_getScheffeGaussian`, X, order)
}

getICritValueGaussian <- function(X, order, q, W) {
    .Call(`_opdesmixr_getICritValueGaussian`, X, order, q, W)
}

mixtureCoordinateExchangeGaussian <- function(X_orig, order, n_cox_points, max_it, verbose, opt_crit, W) {
    .Call(`_opdesmixr_mixtureCoordinateExchangeGaussian`, X_orig, order, n_cox_points, max_it, verbose, opt_crit, W)
}

getXsMNL <- function(X, s) {
    .Call(`_opdesmixr_getXsMNL`, X, s)
}

getUsMNL <- function(X, beta, s, Xs) {
    .Call(`_opdesmixr_getUsMNL`, X, beta, s, Xs)
}

getPsMNL <- function(X, beta, s, Xs) {
    .Call(`_opdesmixr_getPsMNL`, X, beta, s, Xs)
}

getInformationMatrixMNL <- function(X, beta) {
    .Call(`_opdesmixr_getInformationMatrixMNL`, X, beta)
}

getDCritValueMNL <- function(X, beta, verbose) {
    .Call(`_opdesmixr_getDCritValueMNL`, X, beta, verbose)
}

getICritValueMNL <- function(X, beta, verbose, W) {
    .Call(`_opdesmixr_getICritValueMNL`, X, beta, verbose, W)
}

findBestCoxDirMNL <- function(cox_dir, X_in, beta, k, s, opt_crit_value_best, verbose, opt_crit, W) {
    .Call(`_opdesmixr_findBestCoxDirMNL`, cox_dir, X_in, beta, k, s, opt_crit_value_best, verbose, opt_crit, W)
}

mixtureCoordinateExchangeMNL <- function(X_orig, beta, n_cox_points, max_it, verbose, opt_crit, W) {
    .Call(`_opdesmixr_mixtureCoordinateExchangeMNL`, X_orig, beta, n_cox_points, max_it, verbose, opt_crit, W)
}

